### ISSUE TITLE
Use POSIX shell syntax

### ISSUE THREAD

**Issue by Jackojc** [danr/kakoune-easymotion#20]
I'm having an issue with easymotion where it expects me to have bash set as my shell but I use dash for non-interactive scripts (i.e. /bin/sh -> dash).

Would it be possible to refactor the code to use POSIX shell syntax?

I get this error currently `/bin/sh: 2: /bin/sh: [[: not found` which is due to POSIX shell not supporting double bracket expressions which are bash specific.

easymotion _used_ to work for me but I tried using the latest master and it seems to have broken, I can't say when exactly it broke though.

**Comment by danr** [comment]
It's the `_onkey` function function defined here:
https://github.com/danr/kakoune-easymotion/blob/master/easymotion.kak#L66
Do you know how to make it work in dash?

**Comment by Jackojc** [comment]
Well dash is just one shell, POSIX sh is like the standardized syntax for shell script that pretty much _all_ shells implement so it's very portable.

I think this should work: 
```sh
def _on_key -hidden -params .. %{
    on-key %{ eval %sh{
        while [ $# -lt 1 ]; do
            key=$1; shift
            cmd=$1; shift
            if [ $kak_key = $key ]; then
                echo "$cmd"
                exit;
            fi
        done
        echo "$1"
    }}
}
```

I also get this error though, `Error: 1:2: 'eval' no such command: 'a'` when I enter easy-motion-w and attempt to jump to one of the displayed character.

**Comment by danr** [comment]
Thanks! I think yours didn't work because it changed `>` to `-lt`.

**Comment by Jackojc** [comment]
Oh lol, I must've been tired. :sweat_smile:
