### ISSUE TITLE
Broken on current master: easy-motion-on-selections ... too many values to unpack

### ISSUE THREAD

**Issue by vollia** [danr/kakoune-easymotion#21]
Hello,

thanks for the great plugin,
I am using kakoune compiled from the git repository and it seems a bug have appeared somewhere in between [b8eef](https://github.com/mawww/kakoune/commit/b8eef27e041ce68fda01f66e3cc902e97b25fbaf) and [aad4612](https://github.com/mawww/kakoune/commit/aad46123876e264a4bfa9b08a88a1dda0e05b608) (current master)
When triggering an easymotion command, I see corresponding targets selected (each lines for line mode, each word for word mode...) but no indicator.
Also, the debug buffer tells me:
```
easy-motion-on-selections -params 0..3 error: too many values to unpack (expected 2)
```
I can help debugging this if needed.

Charles

**Comment by danr** [comment]
Thanks. I likely won't have time to look into this for a while so feel free to debug it :)

**Comment by vollia** [comment]
found the culprit: 0a66eb9c47ba9a7d3b90286d66a70b5bd7eee15a
will try to solve this in the forthcoming days
