### ISSUE TITLE
error after install : 'echo' unknown option '-to-file' 

### ISSUE THREAD

**Issue by joeitu** [danr/kakoune-easymotion#23]
Hello I just installed the plugin and this is the error I got after trying `easy-motion-char` and `easy-motion-WORD` : 

```
*** This is the debug buffer, where debug info will be written ***
Config-change detected:
Config-change detected:
Error: 1:2: 'easy-motion-on-regex' 6:148: 'easy-motion-on-selections' 2:14: 'echo' unknown option '-to-file'
Error: 1:1: 'easy-motion-WORD' 1:2: 'easy-motion-on-regex' 6:148: 'easy-motion-on-selections' 2:14: 'echo' unknown option '-to-file'
```

Both command does selection of char or words, but throw the error right after.

**Comment by Delapouite** [comment]
Hi the `-to-file` flag has been added in kakoune `20190701`. Which version are you using?

**Comment by joeitu** [comment]
I have install it through package manage on lubuntu. 
`kak -version` give me `Kakoune unknown` :/

I'm gonna try to compile it from github
